# Generated by Django 4.2.23 on 2025-08-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='media_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Media image',
                'verbose_name_plural': 'Media images',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Bela Crochet', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('palette_primary', models.CharField(default='#f5e9e5', help_text='Primary brand colour', max_length=7)),
                ('palette_secondary', models.CharField(default='#caa6c7', help_text='Secondary brand colour', max_length=7)),
                ('palette_accent', models.CharField(default='#e3d4e6', help_text='Accent colour', max_length=7)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
