# Generated by Django 5.2.5 on 2025-08-17 17:12

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=orders.models.generate_order_number, editable=False, max_length=30, unique=True),
        ),
    ]
